# Generated by Django 4.2.8 on 2023-12-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('width', models.CharField(max_length=64)),
                ('height', models.CharField(max_length=64)),
                ('sale_commission', models.FloatField(default=0)),
                ('shop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.shoptype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('shops', models.ManyToManyField(related_name='product_categories', to='marketapp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('photo', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(null=True)),
                ('key_words', models.TextField(blank=True, null=True)),
                ('product_category', models.ManyToManyField(to='marketapp.productcategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketapp.shop')),
            ],
        ),
    ]
